[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "redpandas-ml"
version = "0.3.4"
description = "Enterprise-grade ML data-preparation pipeline with integrated visual health reporting"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "Kuldeep Gade", email = "your-actual-email@gmail.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=1.5",
    "numpy>=1.23",
    "matplotlib>=3.6",
    "seaborn>=0.12",
    "scipy>=1.10",
    "scikit-learn>=1.2"
]

[project.urls]
Homepage   = "https://github.com/GadeKuldeep/redPandas"
Repository = "https://github.com/GadeKuldeep/redPandas.git"
Issues     = "https://github.com/GadeKuldeep/redPandas/issues"

[tool.setuptools.packages.find]
where = ["src"]
